version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - rm -f .env.production && echo "REACT_APP_DOMAIN=${API_DOMAIN}" > .env.production
      - npm config set registry http://registry.npmjs.org
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build s3://$S3_BUCKET
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"
cache:
  paths:
    - 'node_modules/**/*'
